kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dd-managed-ssd-5g
  annotations:
    volume.beta.kubernetes.io/storage-class: managedssd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
