apiVersion: v1
kind: Pod
metadata:
 name: fibre-channel-example-pod
spec:
 containers:
   - image: kubernetes/pause
     name: fc
     volumeMounts:
       - name: fc-vol
         mountPath: /mnt/fc
 volumes:
   - name: fc-vol
     fc:
       targetWWNs:
         - <ADD Target WWN Here>
       lun: <ADD LUN ID Here>
       fsType: ext4
       readOnly: true
