kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sio-small
spec:
  storageClassName: sio-small
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sio-small
