apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: QVFCMTZWMVZvRjVtRXhBQTVrQ1FzN2JCajhWVUxSdzI2Qzg0SEE9PQ==  # the base64-encoded string of the already-base64-encoded key `ceph auth get-key` outputs
